# Generated by Django 3.1.7 on 2021-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcv',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcv',
            name='file',
        ),
        migrations.RemoveField(
            model_name='postcv',
            name='text',
        ),
        migrations.RemoveField(
            model_name='postcv',
            name='title',
        ),
        migrations.AddField(
            model_name='postcv',
            name='upload',
            field=models.FileField(default='NULL', upload_to='uploads/'),
        ),
    ]
