# Generated by Django 3.1.7 on 2021-03-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcv',
            name='description',
        ),
        migrations.RemoveField(
            model_name='postcv',
            name='file',
        ),
        migrations.RemoveField(
            model_name='postcv',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='postcv',
            name='title',
        ),
    ]
