# Generated by Django 3.1.7 on 2021-03-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0002_auto_20210314_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcv',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcv',
            name='file',
            field=models.FileField(default='NULL', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='postcv',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcv',
            name='title',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
