# Generated by Django 3.1.7 on 2021-03-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0003_auto_20210314_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcv',
            old_name='file',
            new_name='fileCV',
        ),
    ]
