# Generated by Django 3.1.7 on 2021-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nos_projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
