# Generated by Django 3.1.7 on 2021-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nos_projets', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
