# Generated by Django 3.1.7 on 2021-03-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nos_projets', '0004_auto_20210314_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='nos_projets/static/images'),
        ),
    ]
